[package]
name = "kristforge"
version = "0.1.0"
authors = ["apemanzilla <dominic@marcuse.us>"]

[dependencies]
structopt = "0.2.12"
reqwest = "0.9.2"
ocl = "0.19.1"
ocl-extras = "0.1.1"
ascii_tree = "0.1.1"
regex = "1.0.5"
lazy_static = "1.1.0"
